# Site settings
title: 零博客 2025.Q4
description: >- # this means to ignore newlines until "baseurl:"
  Read blog on demand.
baseurl: "/25q4" # the subpath of your site, e.g. /blog
url: "https://agora0.github.io" # the hostname & protocol, e.g. http://example.com
github_username: agorahub

# Build settings
timezone: Asia/Singapore
theme: minima
paginate: 50
plugins:
  - jekyll-feed
  - jekyll-paginate

